version: '3.9'

services:
  db:
    build: ./dokcer
    container_name: healthcare_db
    restart: always
    env_file:
      - ./docker/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - healthcare_network
  
  adminer:
    image: adminer
    container_name: healthcare_adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - healthcare_network
  
  volumes:
    pgdata:
  
  networks:
    healthcare_network:
      driver: bridge